---

- name: Copy GitLab-Pgbouncer configuration file.
  template:
    src: pgbouncer.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0644

- name: Create .pgpass file
  command: gitlab-ctl write-pgpass --host 127.0.0.1 --database pgbouncer --hostuser gitlab-consul
  args:
    stdin: "pgbouncer\npgbouncer\n"
    #creates: /var/opt/gitlab/postgresql/.pgpass

#- name: Reconfigure pgbouncer
#  command: gitlab-ctl reconfigure

#- name: Reconfigure pgbouncer
#  command: gitlab-ctl stop

#- name: Reconfigure pgbouncer
#  command: gitlab-ctl start

#- name: Reconfigure pgbouncer
#  command: gitlab-ctl restart consul
