---

- name: Copy GitLab configuration file.
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0644

- name: Reconfigure and start GitLab
  command: gitlab-ctl reconfigure
