# Vagrant file for GitLab deployment

PUBLIC_KEY = File.read(File.expand_path('~/.ssh/id_rsa.pub')).strip
VAGRANT_BOX = 'ubuntu/xenial64'
VAGRANT_PROVIDER = 'virtualbox'

# Virtual Machine settings
VM_HOSTNAME = 'gitlab-deployment'
VM_MEMORY = 2048
VM_CPUS = 2

# Multiple Machines
VM_NAME = 'gitlabVM'
VM_PRIVATE_IP = '10.0.0.101'

Vagrant.configure('2') do |config|

  config.vm.box = VAGRANT_BOX
  config.vm.hostname = VM_HOSTNAME
  config.vm.provider VAGRANT_PROVIDER do |vb|
    vb.name = VM_HOSTNAME
    vb.memory = VM_MEMORY
    vb.cpus = VM_CPUS
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "#{PUBLIC_KEY}" >> /home/ubuntu/.ssh/authorized_keys
    apt-get -y update
    apt-get -y upgrade
    apt-get -y autoremove
    apt-get install -y vim
    apt-get install -y software-properties-common python-software-properties
    add-apt-repository ppa:longsleep/golang-backports -y
    add-apt-repository ppa:git-core/ppa -y
    apt-get -y update
    apt-get install -y git postgresql postgresql-client postgresql-contrib libpq-dev redis-server libicu-dev cmake g++ libre2-dev libkrb5-dev libsqlite3-dev golang-1.10-go ed pkg-config graphicsmagick
    apt-get -y upgrade
    apt-get install -y build-essential zlib1g-dev libyaml-dev libssl-dev libgdbm-dev libre2-dev libreadline-dev libncurses5-dev libffi-dev curl openssh-server checkinstall libxml2-dev libxslt-dev libcurl4-openssl-dev libicu-dev logrotate rsync python-docutils pkg-config cmake
  SHELL

  config.vm.define VM_NAME do |vm1|
    vm1.vm.network "private_network", ip: VM_PRIVATE_IP
  end
end
