- name: Machines Provisioning
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: gcp
      vars:
        gcp_zone: us-east1-b
        gcp_region: us-east1
        gcp_project: copper-gear-221110
        gcp_cred_kind: serviceaccount
        gcp_cred_file: ../.gcloud/gcloud.json
        gcp_machine_type: n1-standard-2
        source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20181030
        disk_size: 12
        disks:
          - disk-01
        addresses:
          - addr-01
        instances:
          - { index: 1, tag: app }

#- name: Create Users
#  hosts: all
#  become: yes
#  roles:
#    - { role: users, payload: users.yml }
