---

- name: Copy GitLab-Redis configuration file.
  template:
    src: redis.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0644
    

- name: Reconfigure Redis
  command: gitlab-ctl reconfigure
