---

- name: Copy Consul configuration file.
  template:
    src: consul.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0644

- name: Reconfigure and start Consul
  command: gitlab-ctl reconfigure
